version: '3.8'

services:
  app:
    platform: linux/arm64
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"  # Adjust if needed
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
 